wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1683065170.020645
    t:
      1:
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
n_epochs:
  desc: null
  value: 5
